name: 'Jekyll Deploy Action'

description: >
  A Github Action to deploy the Jekyll site conveniently for GitHub Pages

branding:
  icon: 'command'
  color: 'red'

inputs:
  id:
    description: The deploy id
    required: false
  hub_username:
    description: Username for Docker Hub
    default: ${{ github.actor }}       
    required: true
  hub_password:
    description: Docker Hub authentication token
    required: true
  hub_token:
    description: Docker Hub authentication token
    required: true
  action_path:
    description: Path to the dockerfile from which to build the image
    required: true
  credentials:
    description: 'The gcloud credentials'
    required: true
  image_name:
    description: Tag to use for the new image
    required: true
  dockerfile_path:
    description: Path to the dockerfile from which to build the image
    required: true
  pauli_sum:
    description: Build args
    required: false
    default: ""
  docker_hub_repo_short_description:
    description: Short description text for the docker hub repo
    required: true
  docker_hub_repo_readme_file_path:
    description: |
      Path of the md file which will be used as the docker hub repo readme
    required: true
  cache_src:
    description: Path for the docker cache source
    required: false
    default: /tmp/.buildx-cache
  cache_dest:
    description: Path for the docker cache destination
    required: false
    default: /tmp/.buildx-cache-new
  provider:
    description: 'The deploy provider'
    required: true
  owner:
    description: 'The deploy owner'
    required: false
  token:
    description: 'The deploy token'
    required: false
  workspace:
    description: 'The deploy repository'
    required: false
  failure_status:
    description: 'The deploy branch'
    required: false

outputs:
  all_outputs:
    description: Collect all outputs
    value: ${{ toJSON(steps.*.outputs) }}

runs:
  #using: 'node20'
  #main: '.github/run/main.js'
  #post: '.github/run/post.js'
  #post-if: 'success()'
  using: composite
  
  steps:
    - name: 💎 Setup Ruby
      uses: ruby/setup-ruby@v1
      if: runner.os == 'Windows'
      with:
        cache-version: 1
        rubygems: default
        bundler-cache: true
        ruby-version: '3.3.4'
        
    - name: Build Jekyll pages
      if: runner.os == 'Windows'
      id: jekyll_site
      shell: bash
      run: |
        echo -e "\n$hr\nSource Pages\n$hr"
        cd ${RUNNER_TEMP//\\//} && rm -rf gh-source

        TARGET_REPO="https://${{ github.actor }}:${{ inputs.token }}@github.com/$TARGET_REPOSITORY.git"
        git clone --single-branch --branch gh-source $TARGET_REPO gh-source && cd gh-source && ls -al .

        echo -e "\n$hr\nBuild Pages\n$hr"
        #Jekyll Quick Reference https://gist.github.com/DrOctogon/bfb6e392aa5654c63d12
        JEKYLL_GITHUB_TOKEN=${{ inputs.token }} DISABLE_WHITELIST=true bundle exec jekyll build --profile -t -p ${RUNNER_TEMP//\\//}/_plugins -d ${RUNNER_TEMP//\\//}/docs

        if [[ "${TARGET_REPOSITORY}" == "eq19/eq19.github.io" ]]; then echo "www.eq19.com" > ${RUNNER_TEMP//\\//}/docs/CNAME; fi
        rm -rf ${RUNNER_TEMP//\\//}/docs/.nojekyll && touch ${RUNNER_TEMP//\\//}/docs/.nojekyll

        echo -e "\n$hr\nFinal Pages\n$hr"
        ls -al ${RUNNER_TEMP//\\//}/docs
        
