name: 'Jekyll Deploy Action'

description: >
  A Github Action to deploy the Jekyll site conveniently for GitHub Pages

branding:
  icon: 'command'
  color: 'red'

inputs:
  id:
    description: The deploy id
    required: false
  hub_username:
    description: Username for Docker Hub
    default: ${{ github.actor }}       
    required: true
  hub_password:
    description: Docker Hub authentication token
    required: true
  hub_token:
    description: Docker Hub authentication token
    required: true
  action_path:
    description: Path to the dockerfile from which to build the image
    required: true
  credentials:
    description: 'The gcloud credentials'
    required: true
  image_name:
    description: Tag to use for the new image
    required: true
  dockerfile_path:
    description: Path to the dockerfile from which to build the image
    required: true
  pauli_sum:
    description: Build args
    required: false
    default: ""
  docker_hub_repo_short_description:
    description: Short description text for the docker hub repo
    required: true
  docker_hub_repo_readme_file_path:
    description: |
      Path of the md file which will be used as the docker hub repo readme
    required: true
  cache_src:
    description: Path for the docker cache source
    required: false
    default: /tmp/.buildx-cache
  cache_dest:
    description: Path for the docker cache destination
    required: false
    default: /tmp/.buildx-cache-new
  provider:
    description: 'The deploy provider'
    required: true
  owner:
    description: 'The deploy owner'
    required: false
  token:
    description: 'The deploy token'
    required: false
  workspace:
    description: 'The deploy repository'
    required: false
  failure_status:
    description: 'The deploy branch'
    required: false
  runner_temp:
    description: 'The deploy branch'
    required: false

outputs:
  all_outputs:
    description: Collect all outputs
    value: ${{ toJSON(steps.*.outputs) }}

runs:
  #using: 'node20'
  #main: '.github/run/main.js'
  #post: '.github/run/post.js'
  #post-if: 'success()'
  using: composite
  
  steps:
    - name: ⏪ Rewind all jobs on failure
      shell: bash
      env:
        BASE: "D:/a/_actions/eq19/eq19/v1/.github"
      run: |
        if [[ '${{ inputs.failure_status }}' == 'true' ]]; then
      
          $BASE/entrypoint/init.sh
          REMOTE_REPO="https://${{ github.actor }}:${{ inputs.token }}@github.com/${{ github.repository }}.git"

          git clone --single-branch --branch gh-pages $REMOTE_REPO gh-pages && cd gh-pages
          git add . && git commit --allow-empty -m "rerun due to job failure" && git push
  
        else

          cd ${{ inputs.workspace }} && rm -rf .git .bundle vendor
          git clone --single-branch --branch gh-pages ${{ env.TARGET_REPO }} ${{ inputs.runner_temp }}/gh-pages

          cd ${{ inputs.runner_temp }}/gh-pages
          find -not -path "./.git/*" -not -name ".git" | grep git
          find -not -path "./.git/*" -not -name ".git" -delete
          
          shopt -s dotglob && mv -f ${{ inputs.workspace }}/* .
          #git fetch && git add . && git commit --allow-empty -m ${{ env.LATEST_COMMIT }} && git rebase && git push
          git add . && git commit --allow-empty -m ${{ env.LATEST_COMMIT }} && git push
         
        fi
